[package]
name = "rust-fetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
detect-desktop-environment = "1.1.0"
os_info = "3.8.2"
